### ISSUE TITLE
The oauth.fail.fast setting is not honoured and Kafka fails to start if JWKS endpoint is not available

### ISSUE THREAD

**Issue by danesss** [strimzi/strimzi-kafka-oauth#174]
## Expected behaviour

If jaas has the setting `oauth.fail.fast=false`, Kafka is able to start even if the JWKS endpoint is unavailable.

## Issue

Kafka fails to start if JWKS endpoint is unavailable, with the following error:

```
[2022-11-03 10:55:59,495] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: java.lang.RuntimeException: Failed to fetch public keys needed to validate JWT signatures: http://10.10.211.7:8080/auth/realms/kafka/protocol/openid-connect/certs
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
        at kafka.network.Processor.<init>(SocketServer.scala:1008)
        at kafka.network.Acceptor.newProcessor(SocketServer.scala:921)
        at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:894)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
        at kafka.network.Acceptor.addProcessors(SocketServer.scala:893)
        at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:600)
        at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:269)
        at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:261)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:261)
        at kafka.network.SocketServer.startup(SocketServer.scala:135)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:309)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.RuntimeException: Failed to fetch public keys needed to validate JWT signatures: http://10.10.211.7:8080/auth/realms/kafka/protocol/openid-connect/certs
        at io.strimzi.kafka.oauth.validator.JWTSignatureValidator.fetchKeys(JWTSignatureValidator.java:306)
        at io.strimzi.kafka.oauth.validator.JWTSignatureValidator.<init>(JWTSignatureValidator.java:167)
        at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.lambda$setupJWKSValidator$1(JaasServerOauthValidatorCallbackHandler.java:357)
        at io.strimzi.kafka.oauth.services.Validators.lambda$get$0(Validators.java:17)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.strimzi.kafka.oauth.services.Validators.get(Validators.java:17)
        at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.setupJWKSValidator(JaasServerOauthValidatorCallbackHandler.java:374)
        at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.configure(JaasServerOauthValidatorCallbackHandler.java:263)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:151)
        ... 18 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
        at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1260)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1208)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at io.strimzi.kafka.oauth.common.HttpUtil.request(HttpUtil.java:152)
        at io.strimzi.kafka.oauth.common.HttpUtil.get(HttpUtil.java:61)
        at io.strimzi.kafka.oauth.validator.JWTSignatureValidator.fetchKeys(JWTSignatureValidator.java:279)
        ... 26 more
[2022-11-03 10:55:59,501] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
```

## Environment

I'm running Kafka v3.2.1 with listeners for both SASL/SCRAM and SASL/OAUTHBEARER.

I use strimzi-kafka-oauth v0.10.0 to configure authentication. Strimzi authorization is not used, but the default AclAuthorizer instead.

OAUTHBEARER listener configuration (this works correctly to authenticate users, but seems to not honour oauth.fail.fast):

```
listener.name.oauth.sasl.enabled.mechanisms=OAUTHBEARER
listener.name.oauth.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
    oauth.jwks.endpoint.uri="http://10.10.211.7:8080/auth/realms/kafka/protocol/openid-connect/certs" \
    oauth.valid.issuer.uri="http://10.10.211.7:8080/auth/realms/kafka" \
    oauth.connect.timeout.seconds="5" \
    oauth.read.timeout.seconds="10" \
    oauth.fail.fast=false \
    oauth.check.audience=true \
    oauth.client.id="broker" \
    oauth.username.claim="myclaim" \
    oauth.fallback.username.claim="username" \
    oauth.fallback.username.prefix="prefix-" \
    unsecuredLoginStringClaim_sub="unused" ;
```

I've tried with the following values in `oauth.fail.fast` and the behaviour was the same:

- `oauth.fail.fast=false`
- `oauth.fail.fast="false"`
- `oauth.fail.fast=true`

**Comment by scholzj** [comment]
Any idea @mstruk?

**Comment by mstruk** [comment]
@danesss When your Kafka broker start ups your logging level for `io.strimzi` is `DEBUG` you should see the effective configuration for JWTSignatureValidator printed. It starts with 'Configured JWTSignatureValidator:'. 

Could you share the output here?

**Comment by mstruk** [comment]
> I use strimzi-kafka-oauth v0.10.0 to configure authentication.

Actually here is your problem. This config setting has been added in 0.11.0.
