### ISSUE TITLE
Kafka Connect as Kafka client with Oauth - Failed to create new KafkaAdminClient

### ISSUE THREAD

**Issue by mroiter-larus** [strimzi/strimzi-kafka-oauth#252]
Hi @scholzj @mstruk 

is there an example of how to use the library on Kafka Connect (for example with a source/sink connector) with Docker?? 

I was able to create a custom image with the library loaded in the classpath but the Kafka Connect worker failed to start.

In my docker compose, the Kafka Connect worker security is configured as follow:

```
      #Connect Worker Security encryption/authentication
      CONNECT_SASL_MECHANISM: OAUTHBEARER
      CONNECT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
        oauth.client.id="kafkaBroker" \
        oauth.client.secret="****" \
        oauth.token.endpoint.uri="https://<keycloak_hostname>:9553/realms/KafkaCluster/protocol/openid-connect/token" \
        oauth.jwks.endpoint.uri="https://<keycloak_hostname>:9553/realms/KafkaCluster/protocol/openid-connect/certs" \
        oauth.username.claim="preferred_username";
      CONNECT_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler

      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/connect.truststore.p12
      CONNECT_SSL_TRUSTSTORE_PASSWORD: *****
      CONNECT_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/connect.keystore.p12
      CONNECT_SSL_KEYSTORE_PASSWORD: *****
      CONNECT_SSL_KEY_PASSWORD: *****
```

The same configuration is replicated also for Kafka Connect producer and consumer by prefixing the same parameters with `CONNECT_PRODUCER_` or `CONNECT_CONSUMER_` as per the (Confluent) Kafka Connect documentation.

I've added also the following ENV variables for the Strimzi SSL setup:

```
      OAUTH_SSL_TRUSTSTORE_LOCATION: /opt/kafka/config/ca-truststore.p12
      OAUTH_SSL_TRUSTSTORE_PASSWORD: changeit
      OAUTH_SSL_TRUSTSTORE_TYPE: PKCS12
      OAUTH_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
```

This is what i got from the Connect logs on the startup:

```
connectOauth  | org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
connectOauth  | 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:551)
connectOauth  | 	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
connectOauth  | 	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
connectOauth  | 	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:136)
connectOauth  | 	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:149)
connectOauth  | Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: An internal error occurred while retrieving token from callback handler
connectOauth  | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
connectOauth  | 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
connectOauth  | 	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
connectOauth  | 	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
connectOauth  | 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:522)
connectOauth  | 	... 4 more
connectOauth  | Caused by: javax.security.auth.login.LoginException: An internal error occurred while retrieving token from callback handler
connectOauth  | 	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:319)
connectOauth  | 	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
connectOauth  | 	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
connectOauth  | 	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
connectOauth  | 	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
connectOauth  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
connectOauth  | 	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
connectOauth  | 	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
connectOauth  | 	at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204)
connectOauth  | 	at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150)
connectOauth  | 	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
connectOauth  | 	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
connectOauth  | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
connectOauth  | 	... 8 more
```

please note that i've already enabled DEBUG logs:

```
      CONNECT_LOG4J_ROOT_LOGLEVEL: "DEBUG"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR,io.strimzi=DEBUG"
```

Thanks in advance for all your precious help!

Mauro

**Comment by mroiter-larus** [comment]
@scholzj i'll give it a try and get back to you. Thanks for your suggestion!

**Comment by mroiter-larus** [comment]
@scholzj 

The properties prefixed with `CONNECT_ADMIN_` were actually missing and i have added them now. 
Having that said, the real problem was related to the Strimzi library's env variables:
```
      OAUTH_SSL_TRUSTSTORE_LOCATION: /opt/kafka/config/ca-truststore.p12
      OAUTH_SSL_TRUSTSTORE_PASSWORD: ****
      OAUTH_SSL_TRUSTSTORE_TYPE: PKCS12
      OAUTH_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
```
which had been incorrectly defined with the prefix `CONNECT_`. After removing it, Kafka Connect worker starts successfully.

Thanks for your support!

I'll try creating a couple of connectors in order to verify that everything is ok!
