### ISSUE TITLE
Unable to start Kafka 3.9.0 in Kraft mode

### ISSUE THREAD

**Issue by juanlucruz** [strimzi/strimzi-kafka-oauth#254]
Hi,

I'm finding issues starting the Kafka Broker when using the Oauth plugin. It's raising this exception:

```
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder for configuration principal.builder.class: Class io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder could not be found. 
at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:778) 
at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:531) 
at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:524) 
at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:115) 
at org.apache.kafka.server.config.AbstractKafkaConfig.<init>(AbstractKafkaConfig.java:70) 
at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:182) 
at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:184) 
at kafka.tools.StorageTool$.$anonfun$execute$1(StorageTool.scala:79) 
at scala.Option.flatMap(Option.scala:283) 
at kafka.tools.StorageTool$.execute(StorageTool.scala:79) 
at kafka.tools.StorageTool$.main(StorageTool.scala:46) 
at kafka.tools.StorageTool.main(StorageTool.scala)
```

I'm using this configuration which is running in the previous step (non Kraft mode)

EDIT: Adding the complete configuration
```
advertised.listeners=PRIVATE://kafka1.<private_domain>:<private_port>,PUBLIC_SSL://kafka1.<public_domain>:<public_port>,INTERNAL_SSL://kafka1.<internal_domain>:<ssl_int_port>,PUBLIC_SASL://kafka1.<public_domain>:<sasl_pub_port>,INTERNAL_SASL://kafka1.<internal_domain>:<sasl_int_port>
authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
auto.create.topics.enable=false
broker.rack=euc1-az2
connection.failed.authentication.delay.ms=1000
controller.listener.names=CONTROLLER
controller.quorum.bootstrap.servers=controller1001.<private_domain>:<controller_port>,controller1002.<private_domain>:<controller_port>,controller1003.<private_domain>:<controller_port>
default.replication.factor=2
delete.topic.enable=true
heap.opts=-Xms2g -Xmx2g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
inter.broker.listener.name=PRIVATE
listener.name.internal_sasl.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.valid.issuer.uri="https://login.microsoftonline.com/<concealed>/v2.0" oauth.jwks.endpoint.uri="https://login.microsoftonline.com/common/discovery/v2.0/keys" oauth.username.claim="azp" oauth.check.access.token.type="false" unsecuredLoginStringClaim_sub="unused" oauth.enable.metrics="true";
listener.name.internal_sasl.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.internal_sasl.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required oauth.token.endpoint.uri="https://login.microsoftonline.com/<concealed>/oauth2/v2.0/token" oauth.valid.issuer.uri="https://login.microsoftonline.com/<concealed>/v2.0" oauth.jwks.endpoint.uri="https://login.microsoftonline.com/common/discovery/v2.0/keys" oauth.scope="<concealed>/.default" oauth.username.claim="azp" oauth.check.access.token.type="false" unsecuredLoginStringClaim_sub="unused" oauth.enable.metrics="true";
listener.name.internal_sasl.plain.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.plain.JaasServerOauthOverPlainValidatorCallbackHandler
listener.name.public_sasl.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.valid.issuer.uri="https://login.microsoftonline.com/<concealed>/v2.0" oauth.jwks.endpoint.uri="https://login.microsoftonline.com/common/discovery/v2.0/keys" oauth.username.claim="azp" oauth.check.access.token.type="false" unsecuredLoginStringClaim_sub="unused" oauth.enable.metrics="true";
listener.name.public_sasl.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.public_sasl.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required oauth.token.endpoint.uri="https://login.microsoftonline.com/<concealed>/oauth2/v2.0/token" oauth.valid.issuer.uri="https://login.microsoftonline.com/<concealed>/v2.0" oauth.jwks.endpoint.uri="https://login.microsoftonline.com/common/discovery/v2.0/keys" oauth.scope="<concealed>/.default" oauth.username.claim="azp" oauth.check.access.token.type="false" unsecuredLoginStringClaim_sub="unused" oauth.enable.metrics="true";
listener.name.public_sasl.plain.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.plain.JaasServerOauthOverPlainValidatorCallbackHandler
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PRIVATE:PLAINTEXT,PUBLIC_SSL:SSL,INTERNAL_SSL:SSL,PUBLIC_SASL:SASL_SSL,INTERNAL_SASL:SASL_SSL
listeners=PRIVATE://0.0.0.0:<private_port>,PUBLIC_SSL://0.0.0.0:<public_port>,INTERNAL_SSL://0.0.0.0:<ssl_int_port>,PUBLIC_SASL://0.0.0.0:<sasl_pub_port>,INTERNAL_SASL://0.0.0.0:<sasl_int_port>
log.dirs=/var/lib/kafka/data
log.retention.hours=720
max.connection.creation.rate=2147483647
max.connections.per.ip.overrides=
node.id=1
num.partitions=3
num.replica.fetchers=1
offsets.retention.minutes=43200
offsets.topic.replication.factor=2
principal.builder.class=io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
process.roles=broker
replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
sasl.enabled.mechanisms=OAUTHBEARER,PLAIN
ssl.client.auth=required
ssl.key.credentials=kafka.key.creds
ssl.key.password=<concealed>
ssl.keystore.credentials=kafka.keystore.creds
ssl.keystore.filename=kafka.keystore.jks
ssl.keystore.location=/etc/kafka/secrets/kafka.keystore.jks
ssl.keystore.password=<concealed>
ssl.truststore.credentials=kafka.truststore.creds
ssl.truststore.filename=kafka.truststore.jks
ssl.truststore.location=/etc/kafka/secrets/kafka.truststore.jks
ssl.truststore.password=<concealed>
super.users=User:ANONYMOUS;User:CN=kafka1.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka2.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka3.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka4.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka5.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka6.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=admin.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>
unclean.leader.election.enabled=false
```

EDIT: Adding more context
We are running Kafka as a Docker container (AWS ECS on EC2) in a custom image based on old Confluent one, very similar to current Kafka official image. Dependencies are downloaded to `/usr/share/java/kafka/` and we have these:
```
accessors-smart-2.5.0.jar
comm-github-json-layout-1.2.17-24d5c10.jar
json-path-2.9.0.jar
json-smart-2.5.0.jar
kafka-oauth-client-0.15.0.jar
kafka-oauth-common-0.15.0.jar
kafka-oauth-keycloak-authorizer-0.15.0.jar
kafka-oauth-server-0.15.0.jar
kafka-oauth-server-plain-0.15.0.jar
nimbus-jose-jwt-9.37.2.jar
```

and this is the Kafka launch command after flight checks
```
java -Xms2g -Xmx2g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80 -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Xlog:gc*:file=/opt/kafka/bin/../logs/kafkaServer-gc.log:time,tags:filecount=10,filesize=100M -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.access.file=/etc/jmx-exporter/jmxremote.access -Dcom.sun.management.jmxremote.password.file=/etc/jmx-exporter/jmxremote.password -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1.dev.playground.public.fdp.3stripes.io -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=<jmx_port> -Dcom.sun.management.jmxremote.port=<jmx_port> -Dkafka.logs.dir=/opt/kafka/bin/../logs -Dlog4j.configuration=file:/etc/kafka/log4j.properties -cp /usr/share/java/kafka/*:/opt/kafka/bin/../libs/activation-1.1.1.jar:/opt/kafka/bin/../libs/aopalliance-repackaged-2.6.1.jar:/opt/kafka/bin/../libs/argparse4j-0.7.0.jar:/opt/kafka/bin/../libs/audience-annotations-0.12.0.jar:/opt/kafka/bin/../libs/caffeine-2.9.3.jar:/opt/kafka/bin/../libs/commons-beanutils-1.9.4.jar:/opt/kafka/bin/../libs/commons-cli-1.4.jar:/opt/kafka/bin/../libs/commons-collections-3.2.2.jar:/opt/kafka/bin/../libs/commons-digester-2.1.jar:/opt/kafka/bin/../libs/commons-io-2.14.0.jar:/opt/kafka/bin/../libs/commons-lang3-3.12.0.jar:/opt/kafka/bin/../libs/commons-logging-1.2.jar:/opt/kafka/bin/../libs/commons-validator-1.7.jar:/opt/kafka/bin/../libs/connect-api-3.9.0.jar:/opt/kafka/bin/../libs/connect-basic-auth-extension-3.9.0.jar:/opt/kafka/bin/../libs/connect-json-3.9.0.jar:/opt/kafka/bin/../libs/connect-mirror-3.9.0.jar:/opt/kafka/bin/../libs/connect-mirror-client-3.9.0.jar:/opt/kafka/bin/../libs/connect-runtime-3.9.0.jar:/opt/kafka/bin/../libs/connect-transforms-3.9.0.jar:/opt/kafka/bin/../libs/error_prone_annotations-2.10.0.jar:/opt/kafka/bin/../libs/hk2-api-2.6.1.jar:/opt/kafka/bin/../libs/hk2-locator-2.6.1.jar:/opt/kafka/bin/../libs/hk2-utils-2.6.1.jar:/opt/kafka/bin/../libs/jackson-annotations-2.16.2.jar:/opt/kafka/bin/../libs/jackson-core-2.16.2.jar:/opt/kafka/bin/../libs/jackson-databind-2.16.2.jar:/opt/kafka/bin/../libs/jackson-dataformat-csv-2.16.2.jar:/opt/kafka/bin/../libs/jackson-datatype-jdk8-2.16.2.jar:/opt/kafka/bin/../libs/jackson-jaxrs-base-2.16.2.jar:/opt/kafka/bin/../libs/jackson-jaxrs-json-provider-2.16.2.jar:/opt/kafka/bin/../libs/jackson-module-afterburner-2.16.2.jar:/opt/kafka/bin/../libs/jackson-module-jaxb-annotations-2.16.2.jar:/opt/kafka/bin/../libs/jackson-module-scala_2.13-2.16.2.jar:/opt/kafka/bin/../libs/jakarta.activation-api-1.2.2.jar:/opt/kafka/bin/../libs/jakarta.annotation-api-1.3.5.jar:/opt/kafka/bin/../libs/jakarta.inject-2.6.1.jar:/opt/kafka/bin/../libs/jakarta.validation-api-2.0.2.jar:/opt/kafka/bin/../libs/jakarta.ws.rs-api-2.1.6.jar:/opt/kafka/bin/../libs/jakarta.xml.bind-api-2.3.3.jar:/opt/kafka/bin/../libs/javassist-3.29.2-GA.jar:/opt/kafka/bin/../libs/javax.activation-api-1.2.0.jar:/opt/kafka/bin/../libs/javax.annotation-api-1.3.2.jar:/opt/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/kafka/bin/../libs/javax.ws.rs-api-2.1.1.jar:/opt/kafka/bin/../libs/jaxb-api-2.3.1.jar:/opt/kafka/bin/../libs/jersey-client-2.39.1.jar:/opt/kafka/bin/../libs/jersey-common-2.39.1.jar:/opt/kafka/bin/../libs/jersey-container-servlet-2.39.1.jar:/opt/kafka/bin/../libs/jersey-container-servlet-core-2.39.1.jar:/opt/kafka/bin/../libs/jersey-hk2-2.39.1.jar:/opt/kafka/bin/../libs/jersey-server-2.39.1.jar:/opt/kafka/bin/../libs/jetty-client-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-continuation-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-http-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-io-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-security-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-server-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-servlet-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-servlets-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-util-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jetty-util-ajax-9.4.56.v20240826.jar:/opt/kafka/bin/../libs/jline-3.25.1.jar:/opt/kafka/bin/../libs/jopt-simple-5.0.4.jar:/opt/kafka/bin/../libs/jose4j-0.9.4.jar:/opt/kafka/bin/../libs/jsr305-3.0.2.jar:/opt/kafka/bin/../libs/kafka-clients-3.9.0.jar:/opt/kafka/bin/../libs/kafka-group-coordinator-3.9.0.jar:/opt/kafka/bin/../libs/kafka-group-coordinator-api-3.9.0.jar:/opt/kafka/bin/../libs/kafka-metadata-3.9.0.jar:/opt/kafka/bin/../libs/kafka-raft-3.9.0.jar:/opt/kafka/bin/../libs/kafka-server-3.9.0.jar:/opt/kafka/bin/../libs/kafka-server-common-3.9.0.jar:/opt/kafka/bin/../libs/kafka-shell-3.9.0.jar:/opt/kafka/bin/../libs/kafka-storage-3.9.0.jar:/opt/kafka/bin/../libs/kafka-storage-api-3.9.0.jar:/opt/kafka/bin/../libs/kafka-streams-3.9.0.jar:/opt/kafka/bin/../libs/kafka-streams-examples-3.9.0.jar:/opt/kafka/bin/../libs/kafka-streams-scala_2.13-3.9.0.jar:/opt/kafka/bin/../libs/kafka-streams-test-utils-3.9.0.jar:/opt/kafka/bin/../libs/kafka-tools-3.9.0.jar:/opt/kafka/bin/../libs/kafka-tools-api-3.9.0.jar:/opt/kafka/bin/../libs/kafka-transaction-coordinator-3.9.0.jar:/opt/kafka/bin/../libs/kafka_2.13-3.9.0.jar:/opt/kafka/bin/../libs/lz4-java-1.8.0.jar:/opt/kafka/bin/../libs/maven-artifact-3.9.6.jar:/opt/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka/bin/../libs/metrics-core-4.1.12.1.jar:/opt/kafka/bin/../libs/netty-buffer-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-codec-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-common-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-handler-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-resolver-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-transport-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-transport-classes-epoll-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-transport-native-epoll-4.1.111.Final.jar:/opt/kafka/bin/../libs/netty-transport-native-unix-common-4.1.111.Final.jar:/opt/kafka/bin/../libs/opentelemetry-proto-1.0.0-alpha.jar:/opt/kafka/bin/../libs/osgi-resource-locator-1.0.3.jar:/opt/kafka/bin/../libs/paranamer-2.8.jar:/opt/kafka/bin/../libs/pcollections-4.0.1.jar:/opt/kafka/bin/../libs/plexus-utils-3.5.1.jar:/opt/kafka/bin/../libs/protobuf-java-3.25.5.jar:/opt/kafka/bin/../libs/reflections-0.10.2.jar:/opt/kafka/bin/../libs/reload4j-1.2.25.jar:/opt/kafka/bin/../libs/rocksdbjni-7.9.2.jar:/opt/kafka/bin/../libs/scala-collection-compat_2.13-2.10.0.jar:/opt/kafka/bin/../libs/scala-java8-compat_2.13-1.0.2.jar:/opt/kafka/bin/../libs/scala-library-2.13.14.jar:/opt/kafka/bin/../libs/scala-logging_2.13-3.9.5.jar:/opt/kafka/bin/../libs/scala-reflect-2.13.14.jar:/opt/kafka/bin/../libs/slf4j-api-1.7.36.jar:/opt/kafka/bin/../libs/slf4j-reload4j-1.7.36.jar:/opt/kafka/bin/../libs/snappy-java-1.1.10.5.jar:/opt/kafka/bin/../libs/swagger-annotations-2.2.8.jar:/opt/kafka/bin/../libs/trogdor-3.9.0.jar:/opt/kafka/bin/../libs/zookeeper-3.8.4.jar:/opt/kafka/bin/../libs/zookeeper-jute-3.8.4.jar:/opt/kafka/bin/../libs/zstd-jni-1.5.6-4.jar kafka.Kafka /etc/kafka/kafka.properties
```

Disabling SASL configuration and `principal.builder.class` makes the broker to run without issues.

EDIT: Running configuration (with sasl disabled)
```
advertised.listeners=PRIVATE://kafka1.<private_domain>:<private_port>,PUBLIC_SSL://kafka1.<public_domain>:<public_port>,INTERNAL_SSL://kafka1.<internal_domain>:<ssl_int_port>
authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
auto.create.topics.enable=false
broker.rack=euc1-az2
connection.failed.authentication.delay.ms=1000
controller.listener.names=CONTROLLER
controller.quorum.bootstrap.servers=controller1001.<private_domain>:<controller_port>,controller1002.<private_domain>:<controller_port>,controller1003.<private_domain>:<controller_port>
default.replication.factor=2
delete.topic.enable=true
heap.opts=-Xms2g -Xmx2g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
inter.broker.listener.name=PRIVATE
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PRIVATE:PLAINTEXT,PUBLIC_SSL:SSL,INTERNAL_SSL:SSL
listeners=PRIVATE://0.0.0.0:<private_port>,PUBLIC_SSL://0.0.0.0:<public_port>,INTERNAL_SSL://0.0.0.0:<ssl_int_port>
log.dirs=/var/lib/kafka/data
log.retention.hours=720
max.connection.creation.rate=2147483647
max.connections.per.ip.overrides=
node.id=1
num.partitions=3
num.replica.fetchers=1
offsets.retention.minutes=43200
offsets.topic.replication.factor=2
process.roles=broker
replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
ssl.client.auth=required
ssl.key.credentials=kafka.key.creds
ssl.key.password=<concealed>
ssl.keystore.credentials=kafka.keystore.creds
ssl.keystore.filename=kafka.keystore.jks
ssl.keystore.location=/etc/kafka/secrets/kafka.keystore.jks
ssl.keystore.password=<concealed>
ssl.truststore.credentials=kafka.truststore.creds
ssl.truststore.filename=kafka.truststore.jks
ssl.truststore.location=/etc/kafka/secrets/kafka.truststore.jks
ssl.truststore.password=<concealed>
super.users=User:ANONYMOUS;User:CN=kafka1.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka2.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka3.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka4.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka5.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=kafka6.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>;User:CN=admin.<public_domain>,OU=<concealed>,O=<concealed>,L=<concealed>,ST=<concealed>,C=<concealed>
unclean.leader.election.enabled=false
```

Can you help me?

Juan Luis

**Comment by scholzj** [comment]
You should probably start by sharing how you run Kafka (and how you added the plugin to it), the full configs and logs. And not just some snippets. Class not found suggests some misconfiguration?

**Comment by juanlucruz** [comment]
Hi @scholzj thanks for the prompt response, I've updated the issue post with more context, I hope that helps. Thanks

**Comment by scholzj** [comment]
Te classpath configuration seems strange with mixing different ways to load the JARs (path with `*` and with exact JAR names). Given the issue is about classes missing in the classpath, have you tried to fix it and use it in the same way for all classes?

Also, this could be caused by something missing in your container image. In Strimzi, we use / test things based on the Apache Kafka project. But the Confluent Platform is a fork with different JARs included. So that might cause some issues as well. From my experience, it has some weird side-effects sometimes and the _class-not-found_ issues in Java never produce clear errors on what exactly is not found (it is sometimes a completely different class missing than what the log suggests). But I would probably try to start with the classpath.

**Comment by scholzj** [comment]
Plus unfortunately the Kafka code in `ConfigDef` seems to swallow the original exception that it got from Java ... so that makes it even harder to understand what the root cause was.

**Comment by juanlucruz** [comment]
> Te classpath configuration seems strange with mixing different ways to load the JARs (path with `*` and with exact JAR names). Given the issue is about classes missing in the classpath, have you tried to fix it and use it in the same way for all classes?
> 
> Also, this could be caused by something missing in your container image. In Strimzi, we use / test things based on the Apache Kafka project. But the Confluent Platform is a fork with different JARs included. So that might cause some issues as well. From my experience, it has some weird side-effects sometimes and the _class-not-found_ issues in Java never produce clear errors on what exactly is not found (it is sometimes a completely different class missing than what the log suggests). But I would probably try to start with the classpath.

Let me try that (updating the classpath).

We are not using Confluent Platform, but we are just building the docker image in a similar way confluent was doing a while ago but we use Apache Kafka binaries.

**Comment by juanlucruz** [comment]
Hi, quick update. 

Reviewing the startup and how we set the classpath, we realised we were setting the classpath with dependencies after `kafka-storage.sh` is executed, causing this to crash (not really Kafka). Setting the classpath before `kafka-storage.sh` is executed solves the problem.

Thanks for the quick answers and sorry for the noise here.
