### ISSUE TITLE
Kafka cluster startup failed - TLS truststore not detected

### ISSUE THREAD

**Issue by mroiter-larus** [strimzi/strimzi-kafka-oauth#256]
Hi @mstruk @scholzj 

After successfully setting up a single instance cluster (Zookeeper + Kafka + Kafka Connect + Strimzi-Kafka-OAuth library) entirely on Docker, I'm trying to set up a 3-node Kafka cluster on-premises.

I'm having trouble Configuring the TLS truststore. Enabling debug log for Kafka and SSL i found the following exception:

```
 javax.net.ssl|ERROR|10|main|2024-12-17 12:27:04.925 CET|TransportContext.java:370|Fatal (CERTIFICATE_UNKNOWN): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (
 "throwable" : {
   sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
           at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
           at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
           at java.base/sun.security.validator.Validator.validate(Validator.java:264)
           at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
           at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
           at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
           at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226)
           at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169)
           at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
           at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
           at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
           at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
           at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
           at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
           at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
           at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
           at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
           at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
           at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
           at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
           at io.strimzi.kafka.oauth.common.HttpUtil.request(HttpUtil.java:481)
           at io.strimzi.kafka.oauth.common.HttpUtil.post(HttpUtil.java:272)
           at io.strimzi.kafka.oauth.common.OAuthAuthenticator.lambda$post$0(OAuthAuthenticator.java:543)
           at io.strimzi.kafka.oauth.common.HttpUtil.doWithRetries(HttpUtil.java:89)
           at io.strimzi.kafka.oauth.common.OAuthAuthenticator.post(OAuthAuthenticator.java:542)
           at io.strimzi.kafka.oauth.common.OAuthAuthenticator.loginWithClientSecret(OAuthAuthenticator.java:167)
           at io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.handleCallback(JaasClientOauthLoginCallbackHandler.java:418)
           at io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.handle(JaasClientOauthLoginCallbackHandler.java:387)
           at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316)
           at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
           at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
           at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:679)
           at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:677)
           at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
           at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:677)
           at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
           at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204)
           at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150)
           at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:80)
           at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:130)
           at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:194)
           at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:265)
           at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:110)
           at kafka.server.BrokerToControllerChannelManagerImpl.buildNetworkClient$1(BrokerToControllerChannelManager.scala:204)
           at kafka.server.BrokerToControllerChannelManagerImpl.newRequestThread(BrokerToControllerChannelManager.scala:246)
           at kafka.server.BrokerToControllerChannelManagerImpl.<init>(BrokerToControllerChannelManager.scala:183)
           at kafka.server.BrokerToControllerChannelManager$.apply(BrokerToControllerChannelManager.scala:149)
           at kafka.server.KafkaServer.startup(KafkaServer.scala:498)
           at kafka.Kafka$.main(Kafka.scala:114)
           at kafka.Kafka.main(Kafka.scala)
   Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
           at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
           at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
           at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
           at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
           ... 49 more}
 )
```

Please note that i'm running Kafka as root user and i have all the necessary permission to access the folder where the truststore has been created, via the following bash script:

```
openssl req -new -nodes \
        -x509 \
        -days 365 \
        -newkey rsa:2048 \
        -keyout ca.key \
        -out ca.crt \
        -config ca.cnf

cat ca.crt ca.key > ca.pem

PASSWORD=****

# create p12 truststore
keytool -keystore ca-truststore.p12 -storetype pkcs12 -alias my-self-ca -storepass $PASSWORD -keypass $PASSWORD -import -file ca.crt -noprompt
```

Given that i'm using the `KeycloakAuthorizer`, the Strimzi configuration at Kafka's `server.properties` level is: 

```
authorizer.class.name=io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
principal.builder.class=io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
super.users=User:kafkaAdmin;User:service-account-kafkabroker;

strimzi.authorization.kafka.cluster.name=gestione-utenti
strimzi.authorization.delegate.to.kafka.acl=true
strimzi.authorization.grants.refresh.pool.size=10
strimzi.authorization.grants.refresh.period.seconds=30
strimzi.authorization.http.retries=5

strimzi.authorization.client.id=kafkaBroker
strimzi.authorization.client.secret=*****
strimzi.authorization.token.endpoint.uri=https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/token
strimzi.authorization.username.claim=preferred_username

strimzi.authorization.ssl.truststore.location=/<path-to>/ca-truststore.p12
strimzi.authorization.ssl.truststore.password=****
strimzi.authorization.ssl.truststore.type=PKCS12
strimzi.authorization.ssl.endpoint.identification.algorithm=
```

I've also tried to configure the same properties (those with `strimzi.authorization.*` prefix) as ENV variable, defining them with the `OAUTH_` prefix.

Which could be the reason why the library can't find the truststore?

Any suggestion would be really appreciated!

Thanks in advance,

Mauro

**Comment by mstruk** [comment]
The stacktrace points to the problem with OAuth authentication truststore configuration.

See the documentation here: https://github.com/strimzi/strimzi-kafka-oauth?tab=readme-ov-file#configuring-the-tls-truststore
and here: https://github.com/strimzi/strimzi-kafka-oauth?tab=readme-ov-file#configuring-the-oauth2

While you have configured the truststore for authorization using `strimzi.authorization.ssl.*` that only covers the `KeycloakAuthorizer` - that's authorization part. It does not cover the authentication part. In order to cover the specific listener authentication you have to provide the configuration as JAAS parameters, or you can specify it as ENV vars, or system properties which will make it work for all the listeners configured with OAuth.

**Comment by mroiter-larus** [comment]
@mstruk Thanks for your prompt reply.

I've tried your suggestion. Now my setup is composed by:

* a JAAS configuration file

```
KafkaServer {
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required 
        oauth.client.id="kafkaBroker" 
        oauth.client.secret="*****"
        oauth.token.endpoint.uri="https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/token"
        oauth.valid.issuer.uri="https://<keycloak_host>:8443/realms/KafkaCluster"
        oauth.jwks.endpoint.uri="https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/certs"
        oauth.username.claim="preferred_username"
        unsecuredLoginStringClaim_sub="unused";
};

KafkaClient {
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
        oauth.client.id="kafkaBroker"
        oauth.client.secret="*****"
        oauth.token.endpoint.uri="https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/token"
        oauth.jwks.endpoint.uri="https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/certs"
        oauth.username.claim="preferred_username";
};

Client {
   org.apache.zookeeper.server.auth.DigestLoginModule required
   username="kafkaAdmin"
   password="*****";
};
```

which is passed to the Kafka service as JVM parameter by the definition of the `KAFKA_OPTS` env variable:

```
KAFKA_OPTS=-Djava.security.auth.login.config=/<path_to>/kafka_server_jaas.conf
```

* the following set of options into the Kafka's `server.properties`:

```
# Kafka Authentication and Authorization
advertised.listeners=INTERNAL://<kafka-broker01_host>:9092,OAUTH://<kafka-broker01_host>:10092,SSL://<kafka-broker01_host>:11092,CLEAR://<kafka-broker01_host>:12092
listener.security.protocol.map=INTERNAL:SASL_PLAINTEXT,OAUTH:SASL_SSL,SSL:SSL,CLEAR:PLAINTEXT
inter.broker.listener.name=OAUTH
listener.name.oauth.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.oauth.oauthbearer.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
listener.name.oauth.oauthbearer.connections.max.reauth.ms=3600000

ssl.client.auth=required
ssl.truststore.filename=/<path_to>/kafka-broker01.truststore.jks
ssl.truststore.credentials=/<path_to>/kafka-broker01-truststore_creds
ssl.keystore.filename=/<path_to>/kafka-broker01.keystore.jks
ssl.keystore.credentials=/<path_to>/kafka-broker01-keystore_creds
ssl.key.credentials=/<path_to>/kafka-broker01-sslkey_creds
ssl.endpoint.identification.algorithm=

sasl.mechanism.inter.broker.protocol=OAUTHBEARER
sasl.enabled.mechanisms=OAUTHBEARER

super.users=User:kafkaAdmin;User:service-account-kafkabroker;

# Authorizer and Principal builder
authorizer.class.name=io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
principal.builder.class=io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder


# Strimzi Authentication
strimzi.client.id=kafkaBroker
strimzi.client.secret=****
strimzi.token.endpoint.uri=https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/token
strimzi.username.claim=preferred_username
strimzi.valid.issuer.uri=https://<keycloak_host>:8443/realms/KafkaCluster
strimzi.jwks.endpoint.uri=https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/certs

# Strimzi KeycloakAuthorizer 
strimzi.authorization.kafka.cluster.name=my-cluster-name
strimzi.authorization.delegate.to.kafka.acl=true
strimzi.authorization.grants.refresh.pool.size=10
strimzi.authorization.grants.refresh.period.seconds=30
strimzi.authorization.http.retries=5
strimzi.authorization.client.id=kafkaBroker
strimzi.authorization.client.secret=****
strimzi.authorization.token.endpoint.uri=https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/token
strimzi.authorization.username.claim=preferred_username
strimzi.authorization.valid.issuer.uri=https://<keycloak_host>:8443/realms/KafkaCluster
strimzi.authorization.jwks.endpoint.uri=https://<keycloak_host>:8443/realms/KafkaCluster/protocol/openid-connect/certs
```

* the following set of ENV variables:

```
export OAUTH_SSL_TRUSTSTORE_LOCATION=/<path_to>/ca-truststore.p12
export OAUTH_SSL_TRUSTSTORE_PASSWORD=****
export OAUTH_SSL_TRUSTSTORE_TYPE=PKCS12
export OAUTH_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
```

I tried also removing all the `strimzi.*` properties from `server.properties` and defining all of them as ENV variables using the `OAUTH_` prefix.

I still got the same stacktrace. I'm probably misunderstanding the Strimzi documentation and your suggestion.

**Comment by mroiter-larus** [comment]
@mstruk i've solved the problem. The reason was that the CA certificate was not imported into the Java cacerts.

Now i got another "certificate issue" which is weird because the same config works as expected in my Docker environment.

```
javax.net.ssl|WARNING|10|main|2024-12-17 15:54:53.814 CET|CertificateMessage.java:1087|No available authentication scheme
javax.net.ssl|ERROR|10|main|2024-12-17 15:54:53.816 CET|TransportContext.java:370|Fatal (HANDSHAKE_FAILURE): No available authentication scheme (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: No available authentication scheme
          at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
          at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
          at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
          at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
          at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
          at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:972)
          at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:961)
          at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:440)
          at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1246)
          at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1182)
          at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:840)
          at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:801)
          at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
          at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
          at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
          at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
          at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
          at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
          at org.apache.kafka.common.security.ssl.SslFactory$SslEngineValidator.handshake(SslFactory.java:497)
          at org.apache.kafka.common.security.ssl.SslFactory$SslEngineValidator.validate(SslFactory.java:436)
          at org.apache.kafka.common.security.ssl.SslFactory$SslEngineValidator.validate(SslFactory.java:413)
          at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:101)
          at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:204)
          at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:265)
          at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:166)
          at kafka.network.Processor.<init>(SocketServer.scala:1178)
          at kafka.network.Acceptor.newProcessor(SocketServer.scala:1051)
          at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:1011)
          at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
          at kafka.network.Acceptor.addProcessors(SocketServer.scala:1010)
          at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:671)
          at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:278)
          at kafka.network.SocketServer.$anonfun$new$51(SocketServer.scala:224)
          at kafka.network.SocketServer.$anonfun$new$51$adapted(SocketServer.scala:224)
          at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
          at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
          at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
          at kafka.network.SocketServer.<init>(SocketServer.scala:224)
          at kafka.server.KafkaServer.startup(KafkaServer.scala:529)
          at kafka.Kafka$.main(Kafka.scala:114)
          at kafka.Kafka.main(Kafka.scala)}
)
javax.net.ssl|ALL|10|main|2024-12-17 15:54:53.817 CET|SSLEngineImpl.java:825|Closing outbound of SSLEngine
javax.net.ssl|ALL|10|main|2024-12-17 15:54:53.817 CET|SSLEngineImpl.java:786|Closing inbound of SSLEngine
[2024-12-17 15:54:53,821] ERROR [KafkaServer id=1] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:208)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:265)
        at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:166)
        at kafka.network.Processor.<init>(SocketServer.scala:1178)
        at kafka.network.Acceptor.newProcessor(SocketServer.scala:1051)
        at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:1011)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
        at kafka.network.Acceptor.addProcessors(SocketServer.scala:1010)
        at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:671)
        at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:278)
        at kafka.network.SocketServer.$anonfun$new$51(SocketServer.scala:224)
        at kafka.network.SocketServer.$anonfun$new$51$adapted(SocketServer.scala:224)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at kafka.network.SocketServer.<init>(SocketServer.scala:224)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:529)
        at kafka.Kafka$.main(Kafka.scala:114)
        at kafka.Kafka.main(Kafka.scala)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:103)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:204)
        ... 18 more
[2024-12-17 15:54:53,825] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
```

**Comment by mstruk** [comment]
Looks like there is something wrong with the way you created your certificate or imported it into keystore.

For example, see this StackExchange post which you can find by googling the error message that you get:
https://stackoverflow.com/questions/76067294/sslhandshakeexception-no-available-authentication-scheme

**Comment by mroiter-larus** [comment]
I agree. I've used a script provided by Confluent to generate my certificates and keystores/truststores. 
I'll try to regenerate them.

However, this is not a Strimzi Kafka Oauth library's configuration problem anymore.

Thanks for your support!
