### ISSUE TITLE
TopicAuthorizationException while consuming message from topic

### ISSUE THREAD

**Issue by HackRanger** [strimzi/strimzi-kafka-oauth#71]
Hello,

I am able to successfully produce the message using console-producer. But I am getting TopicAuthorizationException while consuming.  I am not able to understand how to configure Keycloak resource and permission to allow consumer clients to provide access.

Here the details about the permission from keycloak for consumer:
![image](https://user-images.githubusercontent.com/3878910/93208090-a1731a00-f779-11ea-89f6-20d78cb8dcaf.png)

My resource definition for my-oauth-topic-4 looks like this:

![image](https://user-images.githubusercontent.com/3878910/93208180-cd8e9b00-f779-11ea-9c1d-625a5b8997d9.png)

Producer permission which is working fine:

![image](https://user-images.githubusercontent.com/3878910/93208377-1b0b0800-f77a-11ea-8ddb-e6e6f93881a6.png)
 

Error from Console Consumer:
```
[2020-09-15 13:59:41,795] WARN [Principal=:2e7e8757-3d60-45ee-a155-441b45310826]: Expiring credential expires at Tue Sep 15 14:04:41 CEST 2020, so buffer times of 60 and 300 seconds at the front and back, respectively, cannot be accommodated.  We will refresh at Tue Sep 15 14:03:42 CEST 2020. (org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin)
[2020-09-15 13:59:42,223] WARN [Consumer clientId=consumer-1, groupId=my-oauth-consumer] Error while fetching metadata with correlation id 2 : {my-oauth-topic-4=TOPIC_AUTHORIZATION_FAILED} (org.apache.kafka.clients.NetworkClient)
[2020-09-15 13:59:42,225] ERROR [Consumer clientId=consumer-1, groupId=my-oauth-consumer] Topic authorization failed for topics [my-oauth-topic-4] (org.apache.kafka.clients.Metadata)
[2020-09-15 13:59:42,226] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [my-oauth-topic-4]
Processed a total of 0 messages
```

Can you please point to a right direct to configure authorization.
Thank you!

**Comment by mstruk** [comment]
Add the following config to your Kafka CR to get more details on the authorization decision which should help you determine what the problem is:

```
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
```

**Comment by HackRanger** [comment]
@mstruk thank you. I am getting the DEBUG logs now. I will update you.

**Comment by HackRanger** [comment]
Hello @mstruk ,

I am getting  Failed to parse Resource. I am defining resource in this format: Topic:my-oauth-topic-4,Group:my-oauth-consumer .


```
[2020-09-17 15:45:12,409] DEBUG User validated (Principal:6797e5ab-f660-423c-b53f-aa068784e172) (io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler)
[2020-09-17 15:45:12,455] DEBUG Authorization grants for user OAuthKafkaPrincipal(User:6797e5ab-f660-423c-b53f-aa068784e172, session:1550945958, token:eyJh**kbCw): [{"scopes":["Read","Alter","Write","Describe","IdempotentWrite","Create","DescribeConfigs","AlterConfigs"],"rsid":"b68b997d-7b10-43c2-82f6-e7c705dea6e4","rsname":"Topic:my-oauth-topic-4,Group:my-oauth-consumer"}] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
[2020-09-17 15:45:12,455] ERROR An unexpected exception has occurred:  (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
java.lang.RuntimeException: Failed to parse Resource: Topic:my-oauth-topic-4,Group:my-oauth-consumer - resource part specified multiple times
        at io.strimzi.kafka.oauth.server.authorizer.ResourceSpec.of(ResourceSpec.java:122)
        at io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer.authorize(KeycloakRBACAuthorizer.java:383)
        at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$authorize$1.apply(KafkaApis.scala:424)
        at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$authorize$1.apply(KafkaApis.scala:424)
        at scala.Option.forall(Option.scala:247)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$authorize(KafkaApis.scala:424)
        at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:1035)
        at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:1035)
        at scala.collection.TraversableLike$$anonfun$partition$1.apply(TraversableLike.scala:314)
        at scala.collection.TraversableLike$$anonfun$partition$1.apply(TraversableLike.scala:314)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.partition(TraversableLike.scala:314)
        at scala.collection.AbstractTraversable.partition(Traversable.scala:104)
        at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:1035)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:116)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:73)
        at java.lang.Thread.run(Thread.java:745)
[2020-09-17 15:45:12,456] DEBUG Authorization DENIED due to error - user: OAuthKafkaPrincipal(User:6797e5ab-f660-423c-b53f-aa068784e172, session:1550945958, token:eyJh**kbCw), cluster: kafka-cluster, operation: Describe, resource: Topic:LITERAL:my-oauth-topic-4,
 permissions: [{"scopes":["Read","Alter","Write","Describe","IdempotentWrite","Create","DescribeConfigs","AlterConfigs"],"rsid":"b68b997d-7b10-43c2-82f6-e7c705dea6e4","rsname":"Topic:my-oauth-topic-4,Group:my-oauth-consumer"}] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer.deny)
```

**Comment by mstruk** [comment]
Ah, you need to break up your resource into two - define two resources rather than one:
- `Topic:my-oauth-topic-4`
- `Group:my-oauth-consumer`

But we could add support for how you tried to use it as it makes sense.

**Comment by HackRanger** [comment]
Sorry. I did not know that specifying the Type while creating the resource was important. Now I am not getting DENY while consuming. But i dont see any operation: Read and I am not getting any data at the consumer.

```
[2020-09-17 16:08:08,226] DEBUG Authorization GRANTED - cluster: kafka-cluster, user: OAuthKafkaPrincipal(User:6797e5ab-f660-423c-b53f-aa068784e172, session:989162815,
token:eyJh**8V6A), operation: Describe, resource: Topic:LITERAL:my-oauth-topic-4
Granted scopes for resource (Topic:*): [Write, Delete, Describe, DescribeConfigs, IdempotentWrite] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer.gran
t)
[2020-09-17 16:08:08,226] DEBUG Authorization grants for user OAuthKafkaPrincipal(User:6797e5ab-f660-423c-b53f-aa068784e172, session:989162815, token:eyJh**8V6A): [{"sc
opes":["Write","Describe","Delete","IdempotentWrite","DescribeConfigs"],"rsid":"0c6d3319-a327-43cb-91c7-f11005cec217","rsname":"Topic:*"},{"scopes":["Read","Describe"],
"rsid":"c526204a-f4a5-4411-a725-2a1b8a07f2bd","rsname":"Group:*"}] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
[2020-09-17 16:08:08,226] DEBUG Authorization GRANTED - cluster: kafka-cluster, user: OAuthKafkaPrincipal(User:6797e5ab-f660-423c-b53f-aa068784e172, session:989162815,
token:eyJh**8V6A), operation: Describe, resource: Group:LITERAL:my-oauth-consumer
Granted scopes for resource (Group:*): [Read, Describe] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer.grant)
```

**Comment by HackRanger** [comment]
Thanks for your help. This problem is resolved.
